package org.hikyaku.mobile.theme

import androidx.compose.ui.graphics.Color

// Colours converted from the web design system (oklch CSS variables) to sRGB.
// Keep this in sync with the source CSS in the web project. Derived container /
// surface roles (which the shadcn token set does not define) were generated to
// stay on the brand hue (~264° indigo).

// --- Light ---
internal val LightPrimary = Color(0xFF19398D)
internal val LightOnPrimary = Color(0xFFF3F5F9)
internal val LightPrimaryContainer = Color(0xFFCADEFF)
internal val LightOnPrimaryContainer = Color(0xFF071F67)
internal val LightSecondary = Color(0xFF0A0A0A)
internal val LightOnSecondary = Color(0xFFF5F7FB)
internal val LightSecondaryContainer = Color(0xFFD6E5FF)
internal val LightOnSecondaryContainer = Color(0xFF071F67)
internal val LightTertiary = Color(0xFF19398D)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFCADEFF)
internal val LightOnTertiaryContainer = Color(0xFF071F67)
internal val LightError = Color(0xFF9B0033)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFED1D4)
internal val LightOnErrorContainer = Color(0xFF750021)
internal val LightBackground = Color(0xFFF3F5FB)
internal val LightOnBackground = Color(0xFF010101)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightOnSurface = Color(0xFF010101)
internal val LightSurfaceVariant = Color(0xFFF5F5F5)
internal val LightOnSurfaceVariant = Color(0xFF454545)
internal val LightOutline = Color(0xFF868686)
internal val LightOutlineVariant = Color(0xFFD7D7D7)
internal val LightInverseSurface = Color(0xFF0A0A0A)
internal val LightInverseOnSurface = Color(0xFFF5F7FB)
internal val LightInversePrimary = Color(0xFF97B7F8)
internal val LightSurfaceTint = Color(0xFF19398D)
internal val LightScrim = Color(0xFF000000)
internal val LightSurfaceDim = Color(0xFFDCDEE2)
internal val LightSurfaceBright = Color(0xFFFFFFFF)
internal val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val LightSurfaceContainerLow = Color(0xFFF7F8FB)
internal val LightSurfaceContainer = Color(0xFFF0F2F6)
internal val LightSurfaceContainerHigh = Color(0xFFE9EBEF)
internal val LightSurfaceContainerHighest = Color(0xFFE3E4E9)

// --- Dark ---
internal val DarkPrimary = Color(0xFF6A8DD8)
internal val DarkOnPrimary = Color(0xFF0A0A0A)
internal val DarkPrimaryContainer = Color(0xFF182F65)
internal val DarkOnPrimaryContainer = Color(0xFFCEDEFF)
internal val DarkSecondary = Color(0xFF171717)
internal val DarkOnSecondary = Color(0xFFFAFAFA)
internal val DarkSecondaryContainer = Color(0xFF212D47)
internal val DarkOnSecondaryContainer = Color(0xFFD4DEF3)
internal val DarkTertiary = Color(0xFF404040)
internal val DarkOnTertiary = Color(0xFFFAFAFA)
internal val DarkTertiaryContainer = Color(0xFF333333)
internal val DarkOnTertiaryContainer = Color(0xFFE4E4E4)
internal val DarkError = Color(0xFFCD6E7B)
internal val DarkOnError = Color(0xFFFAFAFA)
internal val DarkErrorContainer = Color(0xFF550F20)
internal val DarkOnErrorContainer = Color(0xFFFFCED3)
internal val DarkBackground = Color(0xFF050505)
internal val DarkOnBackground = Color(0xFFFAFAFA)
internal val DarkSurface = Color(0xFF0A0A0A)
internal val DarkOnSurface = Color(0xFFFAFAFA)
internal val DarkSurfaceVariant = Color(0xFF262626)
internal val DarkOnSurfaceVariant = Color(0xFFA1A1A1)
internal val DarkOutline = Color(0xFF717171)
internal val DarkOutlineVariant = Color(0xFF2E2E2E)
internal val DarkInverseSurface = Color(0xFFFAFAFA)
internal val DarkInverseOnSurface = Color(0xFF0A0A0A)
internal val DarkInversePrimary = Color(0xFF1B3A8B)
internal val DarkSurfaceTint = Color(0xFF6A8DD8)
internal val DarkScrim = Color(0xFF000000)
internal val DarkSurfaceDim = Color(0xFF050505)
internal val DarkSurfaceBright = Color(0xFF2E2E2E)
internal val DarkSurfaceContainerLowest = Color(0xFF020202)
internal val DarkSurfaceContainerLow = Color(0xFF070707)
internal val DarkSurfaceContainer = Color(0xFF0D0D0D)
internal val DarkSurfaceContainerHigh = Color(0xFF161616)
internal val DarkSurfaceContainerHighest = Color(0xFF222222)
